### ISSUE TITLE
Remove bsStyle from Glyphicon

### ISSUE THREAD

**Issue by jrullmann** [react-bootstrap/react-bootstrap#1121]
Adding bsStyle to a glyphicon adds a size suffix to the rendered html, similar to buttons. But the size suffix is not supported by bootstrap, so this doesn't actually do anything.

For example, given this component:

```
<Glyphicon glyph='random' bsSize='large' />
```

This is the rendered html:

```
<span class="glyphicon glyphicon-lg glyphicon-random" data-reactid=".0.1.0.1.0.0.0"></span>
```

I expected glyphicon-lg to match a bootstrap class and the glyph to appear larger. But glyphicon-lg is not part of bootstrap, so it doesn't do anything.

I suggest removing bsStyle from the glyphicon props so people like me don't spend time trying to figure out why it's not working :)

**Comment by jquense** [comment]
yes this is a limitation of the current way we handle this via a mixin. @AlexKVal is working to refactor it so it makes more sense, and situations like this aren't possible

**Comment by AlexKVal** [comment]
Fixed by #1122

**Comment by jrullmann** [comment]
@AlexKVal Perhaps I'm missing something, but it doesn't look fixed to me. bsStyle and bsSize are still shown the props list of the [Glyphicon Documentation](http://react-bootstrap.github.io/components.html#glyphicons).

**Comment by taion** [comment]
@jrullmann The docs are as of v0.24.4, which unfortunately I released a bit before we merged #1122. The change will land in the next release.
