### ISSUE TITLE
Accessing PropTypes via the main React package is now deprecated, as well as React.createClass

### ISSUE THREAD

**Issue by dcporter44** [react-bootstrap/react-bootstrap#2578]
There are deprecations with the newest version of React. I'm getting these 2 warnings when using react-bootstrap:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

>Portal: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by mokone91** [comment]
+1

**Comment by markatk** [comment]
+1

**Comment by jquense** [comment]
Duplicate

**Comment by v12** [comment]
This error message is now caused by [react-overlays](/react-bootstrap/react-overlays), so track that repo for fix being released (it's already in master but hasn't been published yet).

**Comment by dlong500** [comment]
@v12 Actually react-overlays has been updated and released (v0.7.0).  However, react-bootstrap needs to update the dependency as it still currently pulls in v0.6.12 since minor version increments are treated like a major update when the major version is zero.  So bottom line is we need the dependency on react-overlays bumped to 0.7.0 and another point release of react-bootstrap.

**Comment by danielMensah** [comment]
Is there any update on this issue? Because I have updated react-bootstrap but the errors are still popping out in the console.

**Comment by jquense** [comment]
the update is this has been fixed for 2 weeks

**Comment by zbindenren** [comment]
I still have the issue with the latest version 0.31.0

It comes from the Portal component in Modal Component.

**Comment by jquense** [comment]
You have stale dependencies probably. Remove node_modules and reinstall

**Comment by dlong500** [comment]
Or possibly he is also using another module that depends on an older version of react-bootstrap/react-overlays.

**Comment by zbindenren** [comment]
@jquense That is the first thing I tried. I have the latest version of react-bootstrap:

```bash
web/node_modules/react-bootstrap]↥ master(+10/-11,7)+* ± grep version package.json
  "version": "0.31.0",
```

The strange thing I see, there is no Portal Definition in `es` or `lib` directory:
```bash
node_modules/react-bootstrap]↥ master(+10/-11,7)+* ± grep -r Portal es/ lib/
```

But in the `dist` directory I see exactly the line that I get with chrome dev tools:

```bash
node_modules/react-bootstrap]↥ master(+10/-11,7)+* ± grep -r Portal dist/
...
dist/react-bootstrap.js:        var _Portal = __webpack_require__(204);
dist/react-bootstrap.js:        var _Portal2 = _interopRequireDefault(_Portal);
dist/react-bootstrap.js:         * The Modal offers a few helpful features over using just a `<Portal/>` component and some styles:
dist/react-bootstrap.js:                _Portal2.default,
dist/react-bootstrap.js:        Modal.propTypes = _extends({}, _Portal2.default.propTypes, {
dist/react-bootstrap.js:         * The `<Portal/>` component renders its children into a new "subtree" outside of current component hierarchy.
dist/react-bootstrap.js:         * The children of `<Portal/>` component will be appended to the `container` specified.
dist/react-bootstrap.js:        var Portal = function (_React$Component) {
dist/react-bootstrap.js:          _inherits(Portal, _React$Component);
dist/react-bootstrap.js:          function Portal() {
dist/react-bootstrap.js:            _classCallCheck(this, Portal);
dist/react-bootstrap.js:            return _ret = (_temp = (_this = _possibleConstructorReturn(this, (_ref = Portal.__proto__ || Object.getPrototypeOf(Portal)).call.apply(_ref, [this].concat(args))), _this), _this._mountOverlayTarget = function () {
dist/react-bootstrap.js:          _createClass(Portal, [{
dist/react-bootstrap.js:          return Portal;
dist/react-bootstrap.js:        Portal.displayName = 'Portal';
dist/react-bootstrap.js:        Portal.propTypes = {
dist/react-bootstrap.js:           * A Node, Component instance, or function that returns either. The `container` will have the Portal children
dist/react-bootstrap.js:        exports.default = Portal;
dist/react-bootstrap.js:        var _Portal = __webpack_require__(204);
dist/react-bootstrap.js:        var _Portal2 = _interopRequireDefault(_Portal);
dist/react-bootstrap.js:         * Built on top of `<Position/>` and `<Portal/>`, the overlay component is great for custom tooltip overlays.
dist/react-bootstrap.js:                _Portal2.default,
dist/react-bootstrap.js:        Overlay.propTypes = _extends({}, _Portal2.default.propTypes, _Position2.default.propTypes, {

```

**Comment by zbindenren** [comment]
@dlong500 No I have not that dependency.

**Comment by dlong500** [comment]
@zbindenren You should probably post on Stack Overflow.  Also, no one can really do much testing unless you can reproduce the issue in a public repository that others can see and test themselves.

**Comment by danielMensah** [comment]
@zbindenren is right, I actually have the same issue, although reinstalling react-bootstrap twice. However, I will post it on Stack Overlow as @dlong500 suggests.

**Comment by zbindenren** [comment]
@danielMensah can you post the link here?
