### ISSUE TITLE
Forms supported controls example 

### ISSUE THREAD

**Issue by VonTran** [react-bootstrap/react-bootstrap#2933]
![error](https://user-images.githubusercontent.com/15680299/34638941-1701dd48-f2a4-11e7-8f4c-cb28787de801.png)

**Comment by mengwong** [comment]
farther up the page, https://react-bootstrap.github.io/components/forms/?#forms gives this error in the console:

```
Uncaught TypeError: this.setState is not a function
    at handleChange (eval at s (evalCode.js:18), <anonymous>:30:10)
    at Object.executeOnChange (LinkedValueUtils.js:130)
```

**Comment by taion** [comment]
Seems like this is happening because React Live uses Buble v0.15, which doesn't support object rest properties.

@jquense Can we get them to upgrade to a more recent Buble version? It looks like Buble added support here in v0.17: https://github.com/Rich-Harris/buble/blob/master/CHANGELOG.md#0170.

**Comment by taion** [comment]
PRed https://github.com/FormidableLabs/react-live/pull/51. Let's see how that goes.

**Comment by taion** [comment]
We fixed the error up the page in https://github.com/react-bootstrap/react-bootstrap/pull/2932.

**Comment by justbill2020** [comment]
this is still an issue... and #2932 still hasn't fixed the isssue on the page

**Comment by taion** [comment]
I pinged the React Live maintainers again.
