### ISSUE TITLE
New version of @restart/context breaks forwardRef import

### ISSUE THREAD

**Issue by jonlong** [react-bootstrap/react-bootstrap#3576]
The [latest version of @restart/context (2.1.3)](https://github.com/react-restart/context/releases/tag/v2.1.3) breaks [this line in ThemeProvider.js](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ThemeProvider.js#L2)

```js
import forwardRef from '@restart/context/forwardRef';
```

Downgrading to 2.1.2 fixes the issue.

**Comment by taion** [comment]
2.1.3 was a bad publish. i unpublished that revision. 2.1.4 is fixed.

**Comment by Boki23m** [comment]
I have installed 2.1.4 and still getting this error: Failed to compile
../node_modules/@restart/context/forwardRef.js
Module not found: Can't resolve 'react' in 'C:\Users\........
How to fix this? I deleted package-lock.json and run npm install but the issue still not resolved.
Any help please

**Comment by wangjess** [comment]
I'm also having this issue. My app won't compile because:
./src/react-bootstrap/ThemeProvider.jsx
Module not found: Can't resolve '@restart/context/forwardRef' in '/mnt/c/Users/Jess/Desktop/portal/src/react-bootstrap'

I don't see where I can downgrade to 2.1.2. I've been just adding the relevant folders for ProgressBar into my React project directories and I found this issue and can't resolve it.

**Comment by mmarovich** [comment]
Also getting this issue.  Anyone found a fix?
