### ISSUE TITLE
Browser Support: Modal does not work in IE10

### ISSUE THREAD

**Issue by denisplaster** [react-bootstrap/react-bootstrap#3626]
Bootstrap modal works in ie10, but not react-bootstrap modal. Is there a simple way to get this to work?

**Comment by bpas247** [comment]
Do you have an example of this? GitHub repo, CodeSandbox, screenshots, etc.

**Comment by denisplaster** [comment]
Which part would you like an example of? console.log error for modal in ie10? 
Component for modal?

**Comment by denisplaster** [comment]
Modal component..
```
<Modal show={this.state.alertShow} 
          onHide={this.handleCloseAlert}
          {...this.props}
          data-toggle="modal"
          size="sm"
          aria-labelledby="contained-modal-title-vcenter"
          centered>
          <Modal.Header closeButton>
            <Modal.Body>No results found</Modal.Body>
          </Modal.Header>
        </Modal>
```
Error I get in console.
```
[object Error]{description: "Unable to s...", message: "Unable to s...", name: "TypeError", number: -2146823281, stack:
Unhandled promise rejection TypeError: Unable to set property 'paddingRight' of undefined or null reference
```
I have not made any changes to paddingRight. There is also one that says Unable to get property modal

**Comment by taion** [comment]
Hmm, we are transpiling for IE 10: https://github.com/react-bootstrap/configs/blob/5c821e17c07d529ab1607a9472024f2f952dbb7c/packages/babel-preset/index.js#L18

Are we missing some sort of polyfill here?

**Comment by denisplaster** [comment]
I am using this polyfil in my index 

<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>

As well as this module.

import 'react-app-polyfill/ie9';

**Comment by denisplaster** [comment]
Everything seems to work except the modal in IE10

**Comment by jquense** [comment]
should be fixed in beta.8!

**Comment by denisplaster** [comment]
Has this been tested? I'm still getting the same blank screen result.
