### ISSUE TITLE
Syntax errors in IE11

### ISSUE THREAD

**Issue by markbiek** [react-bootstrap/react-bootstrap#3642]
Sample project:
https://github.com/markbiek/playground-template/tree/feature/ie11 

(uses Webpack 4, babel, babel-polyfill, etc)

The above project is a very minimal React 16 app which includes a single reference to a react-bootstrap component.

In IE11, I get syntax errors because there are `...` (spread operators) and references to `const` in the webpack bundle.

It doesn't seem like the react-bootstrap dist file is ES5 compatible and Babel doesn't transpile files in packages.

Am I missing something or doing something wrong? Any suggestions?

**Comment by jquense** [comment]
should be fixed in beta.8!

**Comment by markbiek** [comment]
@jquense Thanks for the quick reply!

I updated to beta.8 and it's still not working, although it does seem that the ES6 code is transpiled out. 

Now I'm getting a `TypeError: Function expected` error.

**Comment by jquense** [comment]
do you have a specific line that it's failing on? the error isn't very helpful and my (quick) look through the compiled code din't turn up es6 code

**Comment by markbiek** [comment]
Let me see if I can narrow down a bit.

Thanks again for the time. I appreciate it a great deal!

**Comment by markbiek** [comment]
OK, I'm just a dope.

After removing my package-lock.json and node_modules/ directory and starting fresh, beta.8 is working perfectly in IE11.
