### ISSUE TITLE
Carousel is not correctly sliding from first index to last in 'prev' direction

### ISSUE THREAD

**Issue by TheKvist** [react-bootstrap/react-bootstrap#3654]
When on the first slide and triggering a slide event in 'prev' direction, the carousel slides to the correct element, the last slide, but with a 'next' animation. This can, for example, be observed in the documentation here:

https://react-bootstrap.github.io/components/carousel/#example

The documentation uses 1.0.0-beta.6, but I haven't had any success with 1.0.0-beta.7 or 1.0.0-beta.8.
The effect is most apparent when repeatedly sliding to the previous slide. The transition from first to last is simply off.

For comparison the expected behavior from the Bootstrap carousel:

https://getbootstrap.com/docs/4.0/components/carousel/#with-controls

Unfortunately my knowledge in this area is so limited that I can't even find the event handler responsible for the actual transition, so I don't actually know where to look for this, but maybe one of you guys know why this is happening.

**Comment by taion** [comment]
it's in https://github.com/react-bootstrap/react-bootstrap/blob/cf5c2a0c8e79bca05982826bc2aa466d928a6abf/src/Carousel.js#L153-L156

we need to handle the case where `previousActiveIndex === 0` and `nextActiveIndex >= lastPossibleIndex`

we'd be happy to take a PR here

**Comment by zhangyu0218** [comment]
if ( 
   (nextIndex === 0 && previousActiveIndex >= lastPossibleIndex) || 
   ( previousActiveIndex !== 0 && previousActiveIndex <= nextIndex)
 )

**Comment by harsh6646** [comment]
I've added the fix above and am in the process of adding tests for it. Will create a PR for it within the next day.

**Comment by jeffreymeng** [comment]
I see that the fix above has been merged, but I'm still having this issue.

**Comment by kosmiq** [comment]
Closing this since a fix has been merged.

**Comment by janis-rasa** [comment]
React-bootstrap version 1.0.1, the problem is still present.

When switching slides (next button) from last to first slide, css classes are incorrectly assigned. Instead of the "carousel-item-left" class, the last slide is assigned the "carousel-item-right". Also, the first slide instead of the "carousel-item-left" class gets "carousel-item-right".
Exactly the same story when switching slides in reverse (prev) order. Instead of the "carousel-item-right" class, the first and last slides get the "carousel-item-left" classes.

https://codesandbox.io/s/runtime-grass-l2cg4?file=/package.json

**Comment by gabrieltcm** [comment]
> React-bootstrap version 1.0.1, the problem is still present.
> 
> When switching slides (next button) from last to first slide, css classes are incorrectly assigned. Instead of the "carousel-item-left" class, the last slide is assigned the "carousel-item-right". Also, the first slide instead of the "carousel-item-left" class gets "carousel-item-right".
> Exactly the same story when switching slides in reverse (prev) order. Instead of the "carousel-item-right" class, the first and last slides get the "carousel-item-left" classes.
> 
> https://codesandbox.io/s/runtime-grass-l2cg4?file=/package.json

Im also facing this problem. Do you know how to fix this issue? I dont quite understand the above fixes.

**Comment by AndrewCi** [comment]
I'm on 1.2.2 and this is still an open issue.
