### ISSUE TITLE
Popper: CSS "margin" styles cannot be used to apply padding

### ISSUE THREAD

**Issue by webcoderkz** [react-bootstrap/react-bootstrap#5081]
## Describe the bug

When you click on `<OverlayTrigger>button here</OverlayTrigger>` it opens a popover, but an error appears in a console: 

"Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers."

## To Reproduce

1. `npx create-react-app sandbox`
2. `yarn add react-bootstrap@1.0.0`
3. Use an OverlayTrigger and click on it.

## Reproducible Example

Codesandbox, nor jsfiddle didn't work at the time i wrote this issue. Heres an example markup:

```
function App() {
  return (
    <div className="App">
      <OverlayTrigger
        trigger="click"
        placement="bottom"
        overlay={<h1>111111</h1>}
      >
        <button>PRESS ME!</button>
      </OverlayTrigger>
    </div>
  );
}
```

Click on the button and watch your console.

## Expected behavior

No warning/error messages should be present in a console.

## Screenshots

![image](https://user-images.githubusercontent.com/5739191/77905522-35265c00-72a8-11ea-8cbf-194fbb4945a2.png)

## Environment (please complete the following information)

- MacOS 10.15.4
- Chrome 80
- React-Bootstrap Version 1.0.0

**Comment by taion** [comment]
That's intentional. Please follow the instructions in the warning message.

**Comment by webcoderkz** [comment]
But i'm not using margin styles. Where could i have these margins?

**Comment by taion** [comment]
`<h1>` by default carries margins

**Comment by smacha-atypon** [comment]
I am not using any margin or padding, and i see same error every time popup opens, and it's happening for basic example. I don't think this ticket should be closed.

```
<OverlayTrigger trigger={['hover', 'focus']} overlay={<Tooltip>Text</Tooltip>}>
<button>click me</button>
        </OverlayTrigger>
```

**Comment by webcoderkz** [comment]
@smacha-atypon yeah, i just found it out either, no components using margins, but still get warnings.

**Comment by kosmiq** [comment]
Not sure what you're getting here or why.

Setting up a test on codesandbox: https://codesandbox.io/s/pedantic-lichterman-htbbt

The expected error of findDomNode appears since strictMode is set for the app. Other than that I see no issues. I do not see any issues running it in a local project either.

Can you fill in with more of what conf you have, other libraries etc. Perhaps there is something in common between your setups that causes this?

**Comment by smacha-atypon** [comment]
@kosmiq here: https://codesandbox.io/s/dawn-cherry-emzmh

**Comment by kosmiq** [comment]
Hmm, thanks. I changed to click here: https://codesandbox.io/s/tender-chaplygin-rnuy2

Inspecting the element reveals the following:
![Screenshot 2020-04-01 at 21 36 25](https://user-images.githubusercontent.com/322759/78179043-dce68a00-7460-11ea-8276-90d47e17b466.png)

Note:
```
.bs-popover-auto[x-placement^=left], .bs-popover-left {
    margin-right: .5rem;
}
```

Disabling that style makes the warning disappear. Not sure why it doesn't happen in the docs though. @taion @jquense  any input here?

**Comment by smacha-atypon** [comment]
It doesn't happen for current version of BS Tooltip, due to solution with padding instead of margin.
I am not sure why it is inconsistent with Popover.
```
.bs-tooltip-left, .bs-tooltip-auto[x-placement^="left"] {
    padding: 0 0.4rem;
}
```
My suggestion would be file ticket and let it be handled by Popper.js or BS. It doesn't look like issue with react-bootstrap, but it's pretty annoying, i have to say, when you use Popups extensively. So i would appreciate some workaround on react-bootstrap side.

Possible workaround seems to be using style override with padding instead of margin.

**Comment by jquense** [comment]
arg yeah, this stinks. I was fairly sure that there was no popper v2 incompatibility issues with bootstrap but that seems to be wrong, at least it's only a warning for now. @FezVrasta sorry to ping you but do you have any workarounds for this? The margin here is not used for distance for for the arrow offset  seems like it's an ok usage?

**Comment by FezVrasta** [comment]
I don't quite get where are margins being used, Popper disallows margins only if applied to the popper element.

**Comment by jquense** [comment]
There is margin on the popper element for `Popover`s but not tooltips. I see why this doesn't occur on the docs site, it's a dev only warning.

**Comment by cduff** [comment]
Note I'm getting same error message with default usage of Dropdown.Menu.

**Comment by miliu99** [comment]
Is there any workaround before this gets fixed?

**Comment by cduff** [comment]
> Is there any workaround before this gets fixed?

FYI I'm working around with Dropdown.Menu by applying {margin: 0 !important;} for the time being.

**Comment by miliu99** [comment]
I just tried on both Overlay and Popover with {margin: 0!important} but it doesn't work.

**Comment by FezVrasta** [comment]
> There is margin on the popper element for `Popover`s but not tooltips. I see why this doesn't occur on the docs site, it's a dev only warning.

You should replace the `[x-placement^=xxxx]` conditional margins with the Popper offset modifier, I'm not sure what you are asking me I'm sorry 😞

**Comment by kosmiq** [comment]
> > There is margin on the popper element for `Popover`s but not tooltips. I see why this doesn't occur on the docs site, it's a dev only warning.
> 
> You should replace the `[x-placement^=xxxx]` conditional margins with the Popper offset modifier, I'm not sure what you are asking me I'm sorry 😞

@jquense this is probably the way to go if we want to be rid of the warning.

A few drawbacks though as I see it:
- We need to override the margin set by the TWBS PopOver (I'm not that fond of overriding upstream styles)
- Set the margins using PopperJS Offsets, but those are in pixels as I understand it and thus the scaling support of em/rem will be lost :(

**Comment by FezVrasta** [comment]
Yeah unfortunately TWBS haven't yet migrated to Popper 2. I'm not sure about a way to preserve em/rem support, you could compute the value reading the font-size of the element, but it wouldn't be responsive in case of dynamic CSS changes.

**Comment by jquense** [comment]
We are unfortunately stuck with whatever the upstream styles are, overriding them isn't really an option since we don't include any css, and inline styles are gonna break customizations. 

@FezVrasta nothing seems broken with the margins, which i would expect to happen. Do you have some sense as to why positioning still seems correct even tho Popper is saying that it won't be?

**Comment by FezVrasta** [comment]
margins mess with the popper box-model, producing visual glitches, especially when the popper gets close to a boundary edge.

**Comment by atomiks** [comment]
Conditional margins cause flicker glitch loops with flipping when the axis changes.

`remToPx` is quite simple:

```js
// you may need to consider iframes too
function remToPx(value) {
  return value * parseFloat(getComputedStyle(document.documentElement).fontSize);
}

remToPx(1.5); // 24

createPopper(reference, popper, {
  modifiers: [
    {
      name: 'offset',
      options: {
        // fully responsive to fontSize changes; 0.5rem margin equivalent
        offset: () => [0, remToPx(0.5)]
      }
    }
  ]
});
```

**Comment by kosmiq** [comment]
@jquense @taion since this will be worked around with @jquense updates for react-overlay and we (probably) won't downgrade to popperjs 1.x, should we close this and add something to the docs about the warning?

**Comment by taion** [comment]
i was suggesting that we add our own helper that deals with the margins at least for stock bootstrap components... we could almost do it in an effect hook, i think. cc @jquense

**Comment by smacha-atypon** [comment]
Working workaround: https://codesandbox.io/s/misty-sun-jldfn

But with newer version of popper.js it seem that this warning is resolved and no longer valid.

**Comment by taion** [comment]
oh what? is this fixed upstream?

**Comment by jquense** [comment]
no i fixed it in #5112 :P

**Comment by KabzM** [comment]
I was getting the same error although I am using react-bootstrap **Dropdown** and not Overlay. The error was appearing every time I clicked on the Dropdown.Toggle button. So I figured something in the Dropdown itself was causing the error.

I managed to get rid of the error by inserting an inline style with margin: 0 on the Dropdown.Menu item.

Like so:

```
<Dropdown.Menu style={{ margin: 0 }}>

    <Dropdown.Item>
          .....
    </Dropdown.Item>

</Dropdown.Menu>
```

Hope it helps someone.

**Comment by FezVrasta** [comment]
note, it's not an error, just a warning, visible only on development environments

**Comment by moniqueboea** [comment]
This worked for me. Thanks

**Comment by trainoasis** [comment]
> note, it's not an error, just a warning, visible only on development environments

Doesn't mean it has to be there - it's quite annoying in development tbh :)

**Comment by jaxramus** [comment]
this is now happening in bootstrap nav dropdowns that i copy and pasted from their docs

its ass

**Comment by garybracket** [comment]
Above commenter is correct..Bootstrap 5.2.0 seems to throw this warning, while 5.1.3 does not.

I copied my nav to a 5.1.3 project from a 5.2.0, and the warning disappeared.

**Comment by tfarah1** [comment]
> ## Describe the bug
> When you click on `<OverlayTrigger>button here</OverlayTrigger>` it opens a popover, but an error appears in a console:
> 
> "Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers."
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. `npx create-react-app sandbox`
> 2. `yarn add react-bootstrap@1.0.0`
> 3. Use an OverlayTrigger and click on it.
> 
> ## Reproducible Example
> Codesandbox, nor jsfiddle didn't work at the time i wrote this issue. Heres an example markup:
> 
> ```
> function App() {
>   return (
>     <div className="App">
>       <OverlayTrigger
>         trigger="click"
>         placement="bottom"
>         overlay={<h1>111111</h1>}
>       >
>         <button>PRESS ME!</button>
>       </OverlayTrigger>
>     </div>
>   );
> }
> ```
> 
> Click on the button and watch your console.
> 
> ## Expected behavior
> No warning/error messages should be present in a console.
> 
> ## Screenshots
> ![image](https://user-images.githubusercontent.com/5739191/77905522-35265c00-72a8-11ea-8cbf-194fbb4945a2.png)
> 
> ## Environment (please complete the following information)
> * MacOS 10.15.4
> * Chrome 80
> * React-Bootstrap Version 1.0.0

I've created a dropwodn list and I was getting this same error whenever I click on it. I solved it by adding style = {{ maring: 0 }} as follows:


<li className="nav-item dropdown">
              <a
                className="nav-link dropdown-toggle m-0"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown List
              </a>
              <ul  


                _**// set margin to 0 to prevent default margin
                style={{ margin: 0 }}**_


                className="dropdown-menu"
                aria-labelledby="navbarDropdown"
              >
                <li>
                  <a className="dropdown-item" href="#">
                    Action
                  </a>
                </li>
                <li>
                  <a className="dropdown-item" href="#">
                    Another action
                  </a>
                </li>
                <li>
                  <hr className="dropdown-divider" />
                </li>
                <li>
                  <a className="dropdown-item" href="#">
                    Something else here
                  </a>
                </li>
              </ul>
            </li>
          </ul>

**Comment by tfarah1** [comment]
I've created a dropwodn list and I was getting this same error whenever I click on it. I solved it by adding style = {{ maring: 0 }} as follows:

              <ul
                // set margin to 0 to prevent default margin
                style={{ margin: 0 }}
                className="dropdown-menu"
                aria-labelledby="navbarDropdown"
              >
                <li>
                  // ....
                </li>
                <li>
                  // ....
                </li>
                
              </ul>

**Comment by am-ramona** [comment]
i was getting the same error with Autocomplete component of Material UI.
It was caused by an attribute 'disablePortal' and disappeared once i removed this attribute, hence i think the margin is applied to a specific attribute of OverlayTrigger too.
Hope this helps!

**Comment by miguelarazede** [comment]
Landed here searching a solution for this warning, while developing in Angular.
I added a ngbTooltip and it started outputing the warn.
Solved with adding _container="body"_ (it's a button in a table cell)

**Comment by phil-w** [comment]
Still getting this with default BS 5. Can't imagine what the message means - it's some kind of riddle thing, right? If only I was smart enough to work it out. Modifiers of what, where?

**Comment by atomiks** [comment]
@phil-w Bootstrap 5 uses a JavaScript library called _Popper_ to position overlay elements like tooltips, popovers, dropdowns and such. This warning is appearing in your console because the popper element that is being positioned has a margin style set on it (non-0) which is not supported by the library. How this can happen:

- The browser’s default styles sometimes has a margin on the element, e.g. `h1`, `ul`, etc. This margin on these elements should be set to `0` before the element gets positioned.
- The authors of Bootstrap placed a margin on a popper element, even though it’s not supported. The `offset` modifier should be being used instead, but it’s not. I’m not sure who is responsible for changing this or why it’s throwing a warning now.

Easiest fix to remove the warning in all instances is to add this to your CSS (_with the caveat of dot point 2 meaning it might now no longer have a proper gap between the reference and popper elements_ — meaning the authors of this library need to fix it at the source):

```css
[data-popper-placement] {
  margin: 0 !important;
}
```

The reason people are confused is because _Popper_ is a transitive dependency that you never actually interact with directly. It's like seeing a warning in the console of Google Chrome because the Chromium developers passed in the wrong thing to a library they're using to build DevTools or something. Hopefully, this is clear.

**Comment by gl-aagostino** [comment]
If you are facing this issue in svelte with flowbite-svelte, here is a solution. Simply add `!m-0` as a class

```ts
<Tooltip class="!m-0">
  No more errors
</Tooltip>
```

**Comment by nbraga** [comment]
Só colocar uma Box onde você está chamando o componente
 
 <Box>
   <IconFilter cleanFilter={() => {}} fnFilter={() => {}}>
        .....
   </IconFilter>
</Box>

**Comment by nbraga** [comment]
` <Box>
                  <IconFilter cleanFilter={() => {}} fnFilter={() => {}}>
                    <Text as="b" fontSize={"md"}>
                      Período de inclusão
                    </Text>
                    <InputDateIcon
                      label="Data de inclusão"
                      nameInput="date-start"
                    />

                    <Text as="b" fontSize={"md"}>
                      Participa de Comissão
                    </Text>
                    <Select
                      variant="flushed"
                      placeholder="Comissão"
                      icon={<RiArrowDownSFill />}
                      onChange={(e) => setSelectCommission(e.target.value)}
                    >
                      {commissions.map((commission) => (
                        <>
                          <option
                            key={commission.ID_COMISSAO}
                            value={commission.DESCRICAO}
                          >
                            {commission.DESCRICAO.charAt(0) +
                              commission.DESCRICAO.slice(1).toLowerCase()}
                          </option>
                        </>
                      ))}
                    </Select>
                  </IconFilter>
                </Box>`

**Comment by nbraga** [comment]
Só colocar o seu Popover, Menu ou Drop dentro de uma Box ou Div e vai parar de dar erro!

**Comment by Oberuks** [comment]
I'm using Bootstrap 5. Adding m-0 helped me:
`<ul class="dropdown-menu m-0">`

**Comment by manfredjb** [comment]
If you are using tailwind and flowbite's dropdown, put close attention to the parent. In the following example, `space-x-1` will trigger the warning:
```
<div class="flex space-x-1">
    <button data-dropdown-toggle="dropdown">...</button>
    <div id="dropdown">...</div>
</div>
```
Some classes change the margin internally.

**Comment by mvthiago** [comment]
> I'm using Bootstrap 5. Adding m-0 helped me: `<ul class="dropdown-menu m-0">`

This solved for me on Bootstrap 5 too, ty.

**Comment by thiu** [comment]
> I'm using Bootstrap 5. Adding m-0 helped me: `<ul class="dropdown-menu m-0">`

This solved for me on Bootstrap 5 too, ty.
