### ISSUE TITLE
TypeScript error: ModalHeader

### ISSUE THREAD

**Issue by Kaiman23** [react-bootstrap/react-bootstrap#5276]
I have events registered on the ModalHeader, it looks like now with the typing in v1.1.x, TypeScript throws an error regarding that event properties don't exist.  It looks like any basic React property will throw this error, e.g. `onClick=`.  However, doing events on other modal components, such as ModalTitle, work normally.  Note: the compiler seems to die on just whatever the first attribute is, as commenting out each red underlined will error on the following event.

### Code:
<img width="641" alt="Screen Shot 2020-07-07 at 4 57 45 PM" src="https://user-images.githubusercontent.com/6288695/86853059-0cfe8400-c073-11ea-9e3f-ee1e63f646e8.png">

### Error:
<img width="754" alt="Screen Shot 2020-07-07 at 4 58 03 PM" src="https://user-images.githubusercontent.com/6288695/86853077-1556bf00-c073-11ea-8130-a54778a8b970.png">

**Comment by scand1sk** [comment]
It seems that the `style` attribute is no longer useable on `Modal.Header` either.

**Comment by kyletsang** [comment]
@jquense are you working on these types issues?  If not, I can take them?

**Comment by jquense** [comment]
I think i fixed this one?

**Comment by Kaiman23** [comment]
I just upgraded to v1.2.0, and the TS compiler now assuaged. ^_^

**Comment by kyletsang** [comment]
> 
> 
> I think i fixed this one?

Ah you're right.  I'll take care of other ones.

Closing this since it's fixed in 1.2.0

**Comment by bcobra** [comment]
I am still seeing this error in 1.3.0:
Type '{ children: Element; }' is missing the following properties from type 'Pick<ModalHeaderProps, "style" | "title" | "slot" | "bsPrefix" | "className" | "role" | "children" | "onHide" | "color" | "id" | "lang" | "tabIndex" | "dangerouslySetInnerHTML" | ... 245 more ... | "closeButton">': translate, onAuxClick, onAuxClickCapturets(2739)

**Comment by Saltallica** [comment]
Same here.. not working in version 1.2.0, 1.2.2, and 1.3.0

To reproduce, use one of your examples on your site.

Why is this closed?

**Comment by kyletsang** [comment]
For those that are still seeing this issue, can you please post a code repro/TS version?  

I am running TS 3.9.6 with react-bootstrap 1.3.0 and I am not seeing the errors using the code in the OP.

**Comment by Falci** [comment]
I got this error on `Modal.Header`

```text
TS2741: Property 'translate' is missing in type '{ children: Element; closeButton: true; }' but required in type 'Pick<ModalHeaderProps, "style" | "title" | "slot" | "children" | "placeholder" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | ... 249 more ... | "closeButton">'.
```

From:
```jsx
    <Modal show onHide={() => navigate('./')} backdrop="static" dialogClassName="modal-90w">
        <Modal.Header closeButton>
            <Modal.Title>{data.name}</Modal.Title>
        </Modal.Header>
        <Modal.Body>
        ...
```

Versions:
```text
yarn list --pattern "typescript|bootstrap" --depth=1
yarn list v1.22.0
├─ @babel/plugin-syntax-typescript@7.10.4
├─ @babel/plugin-transform-typescript@7.11.0
├─ @babel/preset-typescript@7.10.4
├─ bootstrap@4.4.1
├─ react-bootstrap-typeahead@4.0.0-rc.2
├─ react-bootstrap@1.3.0
├─ react-docgen-typescript-loader@3.2.0
├─ react-docgen-typescript@1.14.0
└─ typescript@4.0.3
✨  Done in 0.57s.
```
