### ISSUE TITLE
React bootstrap OverlayTrigger Popover changes its placement when opening and closing

### ISSUE THREAD

**Issue by Hartaithan** [react-bootstrap/react-bootstrap#6314]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I have a Popover that is wrapped in forwardRef and when i open/close it, its placement changes. Also on mobile resolution the Popover appears outside the parent element.

### Expected behavior

 I need the Popover to always be in the parent element and not outside of it.

### To Reproduce

1. Open sandbox (if you get root stylesheet error, refresh sandbox)
2. Click on details button on any character
3. Try open any popover

### Reproducible Example

Sandbox - [link](https://codesandbox.io/s/beautiful-breeze-m24py3)

### Screenshots

![popover](https://user-images.githubusercontent.com/62736094/165898765-2cdb8623-bf24-4a3d-a8e1-29255ed93e17.gif)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.3.0

### What version of Bootstrap are you using?

5.1.3

### Additional context

**OverlayTrigger - src/components/DetailModal**

```
               <div className="detail-modal__item__value episodes">
                {details.episode.map((ep: string) => {
                  return (
                    <OverlayTrigger
                      trigger="click"
                      placement="auto"
                      overlay={<EpisodePopover url={ep} />}
                      container={modalRef}
                      key={ep}
                    >
                      <p>{ep.split("episode/")[1]}</p>
                    </OverlayTrigger>
                  );
                })}
              </div>
```

**Popover - src/components/Popovers/EpisodePopover**

```
const EpisodePopover = React.forwardRef<HTMLDivElement, IPopoverProps>((props, ref) => {
    const { url } = props;
    const [episode, setEpisode] = React.useState<IEpisode>(null);
    const [isLoading, setLoading] = React.useState<boolean>(true);

    React.useEffect(() => {
      axios
        .get(url)
        .then(({ data }) => {
          setEpisode(data);
        })
        .catch((error) => {
          console.error("EpisodePopover", error);
        })
        .finally(() => {
          setLoading(false);
        });
    }, []); // eslint-disable-line

    return (
      <Popover className="popover" id="popover-basic" ref={ref} {...props}>
        <Popover.Body>
          {isLoading ? (
            <Loader />
          ) : (
            <>
              <div className="popover__item">
                <p className="popover__item__title">Name:</p>
                <p className="popover__item__value">{episode.name}</p>
              </div>
              <div className="popover__item">
                <p className="popover__item__title">Episode:</p>
                <p className="popover__item__value">{episode.episode}</p>
              </div>
              <div className="popover__item">
                <p className="popover__item__title">Air date:</p>
                <p className="popover__item__value">{episode.air_date}</p>
              </div>
            </>
          )}
        </Popover.Body>
      </Popover>
    );
  }
);
```

**Comment by isherwood** [comment]
I have this problem as well with a simple series of Tooltip components. In addition to the faulty placement, the page scrollbar briefly shows when the overlay first appears in the DOM. 

`<OverlayTrigger delay={{show: 500}} overlay={renderCopyTooltip} key={cellContent}>
    <Button variant="link" size="sm" className="clipboarder"
            onClick={(event) => copyText(event.currentTarget)}>
        <FaClipboard className='clip-icon'/><FaCheck className='clip-icon'/>
    </Button>
</OverlayTrigger>`

@Hartaithan, your demo link is broken (or unavailable).

**Comment by Hartaithan** [comment]
@isherwood The problem was that my popover had dynamic content and it didn't change its width after changing content. In my case, [this](https://react-bootstrap.github.io/components/overlays/#updating-position-dynamically) helped
Popover - [link](https://github.com/Hartaithan/rick-and-morty-api/blob/main/src/components/Popovers/EpisodePopover.tsx)
Modal - [link](https://github.com/Hartaithan/rick-and-morty-api/blob/main/src/components/DetailModal/DetailModal.tsx)

**Comment by kyletsang** [comment]
@isherwood can you try this with 2.5.0-beta.0?

**Comment by isherwood** [comment]
Thanks. 2.5.0-beta.0 is a definite improvement, but I see a very brief flicker of the tooltip at the edge of the viewport before it assumes the correct position. I don't see the scrollbar anymore.

**Comment by kyletsang** [comment]
@isherwood can you provide a minimum repro?

**Comment by isherwood** [comment]
I don't know if I'll have the time to do that. Here's my package.json --save block, in case anyone else wants to fiddle. 

```
  "dependencies": {
    "bootstrap": "^5.2.0-beta1",
    "react": "^18.1.0",
    "react-bootstrap": "^2.5.0-beta.0",
    "react-bootstrap-table-next": "^4.0.3",
    "react-dom": "^18.1.0",
    "react-icons": "^4.4.0",
    "react-query": "^3.39.1",
    "react-router-dom": "^6.3.0"
  },
```

**Comment by artygrand** [comment]
Demo with 2.5.0-beta.1
https://codesandbox.io/s/aged-wood-wkvkgx?file=/src/App.js

It's positioned but with flicker

**Comment by levanchien** [comment]
> Demo with 2.5.0-beta.1 https://codesandbox.io/s/aged-wood-wkvkgx?file=/src/App.js
> 
> It's positioned but with flicker Component from examples

@artygrand I fixed by add position: absolute to Tooltip
[https://codesandbox.io/s/pedantic-sky-7ge7t1?file=/src/App.js](url)

**Comment by isherwood** [comment]
levanchien, your link is faulty. 

Corrected link](https://codesandbox.io/s/pedantic-sky-7ge7t1?file=/src/App.js)

**Comment by aksdevac** [comment]
This issue is still present in `2.7.0` version, will try to regenerate on codesandbox, initially for split second it displays it on different position (for every trial) & layout shifts in 3 out of 5 trials/hover.

**Comment by furqan72672** [comment]
issue still happening
bootstrap ^5.2.3, react-bootstrap ^2.7.0

**Comment by aksdevac** [comment]
Hi, I can regenerate initial wrong position issue on current docs site see below screenshots:
for initial display (after show class is added) tx value is wrong in `translate3d(tx, ty, tz)`.

Initial/Wrong position: 

<img width="1728" alt="initial-tooltip" src="https://user-images.githubusercontent.com/2557058/216940785-bc7b965c-2852-405c-a6ed-bcbda7418453.png">

Correct position (after some ms):

<img width="1532" alt="correct-pos" src="https://user-images.githubusercontent.com/2557058/216940936-1269f5cb-9eca-40ba-ad89-12e11e281440.png">

You can also check wrong style value by adding state log (before or after setFirstRenderedState) here:
https://github.com/react-bootstrap/react-bootstrap/blob/4bb44894cf10dec511931a243ccb47e742107fe8/src/Overlay.tsx#L173

**Comment by furqan72672** [comment]
is there any solution?

**Comment by furqan72672** [comment]
please solve this bug

**Comment by Silvenga** [comment]
For anyone coming in from Google.

This can occur if you forget to send props to the tooltip from the overlay.

So, for example:

```
export type SimpleTooltipProps = {
    title?: string | null;
    children: React.ReactElement | ((props: OverlayTriggerRenderProps) => React.ReactNode);
}

export function SimpleTooltip({ title, children }: SimpleTooltipProps) {
    let id = useMemo(() => uuid.v4(), []);
    return title
        ? (
            <OverlayTrigger overlay={props => <Tooltip id={id} {...props}>{title}</Tooltip>}>
                {children}
            </OverlayTrigger>
        )
        : <>{children}</>
}

```

Reading the docs also tells you this, the failure mode just doesn't make this obvious.

**Comment by Thomas-Boi** [comment]
Just run into this problem. The doc explains it [here](https://react-bootstrap.github.io/docs/components/overlays/#customizing-overlay-rendering). Basically, Popper needs a few seconds to measure the element before it's positioned properly. The doc recommended using `opacity: 0` to deal with this. Another thing I've found is if you change the `container` prop of `Overlay` to `() => document.querySelector("#root")`, it works as well (albeit for only overlay at a time)
